[package]
name = "bionify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epub = "1.2.3"
nipper = "0.1.9"
zip = "0.6.2"
